MaaAssistantArknights/MaaRelease

.github/workflows/deploy.yml, crontabs
这种情况直接用 git 同步得了.
说起来应该没有从 ota 服务器修改了再 push 回 GitHub 的 main 的需求吧, 这样就复杂了 (~~要改就自己另外 clone 一份来改吧~~
=> chore: sync repo to server automatically

MaaAssistantArknights/api/qqgroup/index.html
=> chore: 更改加群链接

MaaAssistantArknights/api/qqgroup/index.html
=> chore：更新加群链接

MaaAssistantArknights/api/qqgroup/index.html
https://jq.qq.com/?k=NOpUOidq
290949547
=> 更改加群链接到 八群

MaaAssistantArknights/api/qqgroup/index.html
https://jq.qq.com/?_wv=1027&k=h6FGp0qD
645852443
=> 更改加群链接到 四群

MaaAssistantArknights/api/gui/StageActivity.json, MaaAssistantArknights/api/resource/global/txwy/resource/tasks.json
被 [這裡](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/5003#issuecomment-1568677700) 跟 [這裡](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/4636#issuecomment-1534985150) 帶過來的 
有先參考了一下其他服的寫法，應該...是...這樣...吧 (?)
StageActivity 裡的 Drop 是從企鵝物流那邊看來的，資源收集填的是上次台服開放的時間。
再麻煩各位大佬幫忙看看有沒有地方要修改的  ( ｡･-･｡ )
=> feat: 繁中服風雪過境復刻導航

MaaAssistantArknights/api/resource/global/txwy/resource/tasks.json
同 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7085
=> chore: 調整繁中服「照我以火」導航任務

MaaAssistantArknights/api/resource/tasks.json
- https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/7113
=> perf: api to follow main release

MaaAssistantArknights/api/gui/StageActivity.json
=> chore: YoStarJP&KR 塵影に交わる残響 復刻

MaaAssistantArknights/api/gui/StageActivity.json, MaaAssistantArknights/api/resource/global/YoStarEN/resource/tasks.json
=> chore: YostarEN Lingering Echoes rerun stage navigation

MaaAssistantArknights/api/gui/StageActivity.json
=> fix: 修正繁中服「塵影餘音」LE-7 的 value

MaaAssistantArknights/api/gui/StageActivity.json
=> chore:补充搓玉数据

MaaAssistantArknights/api/gui/StageActivity.json
=> chore: YoStar servers new CC season1

MaaAssistantArknights/api/gui/StageActivity.json
=> chore: YostarJP WB navigation fix

MaaAssistantArknights/api/qqgroup/index.html
链接来源：
https://github.com/MaaAssistantArknights/MaaRelease/blob/main/MaaAssistantArknights/api/qqgroup/content_summary.html
=> 修改 QQ 加群链接到 MAA 作业群 10

MaaAssistantArknights/api/gui/StageActivity.json
=> revise: DV -> CV

MaaAssistantArknights/api/qqgroup/content_summary.html, MaaAssistantArknights/api/qqgroup/index.html
更新 “Update content_summary.html” 中 3 群链接
修改 “index.html” 中链接到 MAA作业三裙
=> 修改 QQ 加群链接到 MAA 作业裙 3

MaaAssistantArknights/api/resource/global/YoStarJP/resource/tasks.json
=> chore: fix YostarJP OD navigation

MaaAssistantArknights/api/resource/global/txwy/resource/tasks.json
=> fix: 繁中服 ZT-Open 中的 next

MaaAssistantArknights/api/resource/tasks.json
fix https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/10742
=> fix: temp fix for #10742 until new release

MaaAssistantArknights/api/gui/StageActivity.json, MaaAssistantArknights/api/resource/global/YoStarJP/resource/tasks.json
`BBChapterToBB` text is expected to be difficult to recognize
=> chore: YostarJP BB navigation

MaaAssistantArknights/api/resource/global/txwy/resource/tasks.json
close https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/10795
=> fix: txwy ZT navigation

MaaAssistantArknights/api/resource/global/txwy/resource/tasks.json
=> update: 銀心湖列車 導引

MaaAssistantArknights/api/gui/StageActivity.json
=> feat: SideStory「照我以火」TW

MaaAssistantArknights/api/gui/StageActivity.json
=> feat:臺服 "登臨意" 更新

MaaAssistantArknights/api/gui/StageActivity.json
Reverts MaaAssistantArknights/MaaRelease#230
=> Revert "feat:臺服 "登臨意" 更新"

MaaAssistantArknights/api/resource/platform_diff/iOS/resource/tasks.json
Corresponds to [#11266](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/11266).
=> fix: 为 ios端降低 Sarkaz@Roguelike@DecreaseBurdenAbandonThought 任务模版匹配的 threshold

MaaAssistantArknights/api/gui/StageActivity.json, MaaAssistantArknights/api/resource/global/YoStarKR/resource/tasks.json
Reverts MaaAssistantArknights/MaaRelease#289
=> Revert "feat: YostarKR KR navigation"

MaaAssistantArknights/api/gui/StageActivity.json
=> feat: 怀黍离 复刻 导航

MaaAssistantArknights/api/qqgroup/content_summary.html, MaaAssistantArknights/api/qqgroup/index.html
=> chore: 加群链接 十四群

MaaAssistantArknights/api/resource/global/YoStarEN/resource/tasks.json, MaaAssistantArknights/api/resource/global/YoStarJP/resource/tasks.json, MaaAssistantArknights/api/resource/global/YoStarKR/resource/tasks.json, MaaAssistantArknights/api/resource/global/txwy/resource/tasks.json
Fix bd21e0dd83ae0bc7684ab26073f2bc1bc817e7ec
ref: https://github.com/MaaAssistantArknights/MaaRelease/commit/bd21e0dd83ae0bc7684ab26073f2bc1bc817e7ec#commitcomment-154943930
=> fix: tasks after bd21e0dd83ae0bc7684ab26073f2bc1bc817e7ec

MaaAssistantArknights/api/resource/global/YoStarJP/resource/tasks.json
[480, 450, 320, 60] -> [480, 480, 320, 60]
=> fix: YostarJP StartToWakeUp

MaaAssistantArknights/api/qqgroup/index.html
=> chore: 加群链接 十一群

MaaAssistantArknights/api/gui/StageActivity.json, MaaAssistantArknights/api/resource/global/YoStarEN/resource/tasks.json
30 minutes to go. I forgot to add this yesterday.
=> feat: YostarEN ZT rerun

MaaAssistantArknights/api/qqgroup/index.html
=> chore: 加群链接 十三群

MaaAssistantArknights/api/gui/StageActivity.json, MaaAssistantArknights/api/resource/global/YoStarJP/resource/tasks.json
=> chore: Yostar servers EA navigation

MaaAssistantArknights/api/resource/global/YoStarJP/resource/tasks.json
close https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/14168, https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/14161
=> chore: JP chapter15 start button
